# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.11.2

pipelines:
  custom: # Pipelines that are triggered manually
  generali-life:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - mkdir download
          - chmod 777 download
          - npm test
        services: 
          - mongo
definitions: 
  services: 
    mongo: 
      image: mongo